<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <AssemblyName>Tsonic.CSharp.Node</AssemblyName>
    <RootNamespace>Tsonic.CSharp.Node</RootNamespace>
    <Version>1.0.7</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <!-- Package settings -->
    <IsPackable>true</IsPackable>
    <PackageId>Tsonic.CSharp.Node</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)**/*.cs" Exclude="$(MSBuildThisFileDirectory)bin/**;$(MSBuildThisFileDirectory)obj/**" />
    <None Include="$(MSBuildThisFileDirectory)../../../README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="$(TsonicCsharpRuntimeProject)" />
    <ProjectReference Include="$(TsonicCsharpJsProject)" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
